# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install any needed dependencies specified in package.json
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY src ./src
COPY tsconfig.json ./tsconfig.json

# Build the TypeScript code
RUN npm run build

# Use a minimal Node.js runtime for the final image
FROM node:18-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set environment variable
ENV NODE_ENV=production

# Expose port if needed (change 3000 to the actual port if different)
# EXPOSE 3000

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
